#config.yaml

#folder containing the gene alignments
alignment_folder: "input/Analysis_Folder/"

#csv file indicating the taxonomic structure
#!IMPORtANT! first row of csv file must indicate level 
#!!IMPORTANT!! level name must match exactly: clade, species, id
structure_csv: "input/Isolates_species_clades.csv"

#destination folder for the output (will be created if it does not exist)
output_folder: "output_markerfinder/"

#required ratio of isolates within species/clades to be considered a diagnostic position
threshold: 1.0

#maximum number of marker genes allowed (!currently not used!)
max_genes: 8

#extension after gene names (used for saving the markers to a txt file)
extension: "_MSA_trimmed.fna"
